CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE jiffy_users (userid integer primary key, username VARCHAR(250) NOT NULL, password varchar(256), locale VARCHAR(30) NULL, rowState INT, serverTimeStamp BIGINT, lastChanged BIGINT);
CREATE TABLE jiffy_commit_counter (counter BIGINT, lastChanged BIGINT);
CREATE TABLE jiffy_base_worktimes (userid INT, groupId INT, uuidM BIGINT, uuidL BIGINT, weekday INT, worktime BIGINT, rowState INT, lastChanged BIGINT, local INT, serverTimeStamp BIGINT, primary key(uuidM, uuidL));
CREATE TABLE jiffy_override_worktimes (userid INT, UTC BIGINT, zoneOffset INT, worktime BIGINT, timeLocal BIGINT, rowState INT, uuidM BIGINT, uuidL BIGINT, zoneName TEXT, local int, serverTimeStamp BIGINT, lastChanged BIGINT, primary key(uuidM, uuidL));
CREATE TABLE jiffy_time_tree(userId integer, name VARCHAR(200), color int, archived boolean, worktime boolean, rowState Int, uuidM BIGINT, uuidL BIGINT, parentUuidM BIGINT, parentUuidL BIGINT, local boolean, expanded BOOLEAN, serverTimeStamp BIGINT, lastChanged BIGINT, sharedFromUuidM BIGINT default 0, sharedFromUuidL BIGINT default 0, primary key(uuidM, uuidL));
CREATE TABLE jiffy_compensation(userid INT, type INT, adjustment INT, dayInUTC BIGINT, zoneOffset INT, note TEXT, rowState INT, uuidM BIGINT, uuidL BIGINT, zoneName TEXT, local int, lastChanged BIGINT,  primary key(uuidM, uuidL));
CREATE TABLE jiffy_compensation_cache(userid INT, dayInUTC BIGINT, zoneOffset INT, current INT, rowState INT, lastChanged BIGINT,  primary key(userid, dayInUTC, zoneOffset, rowState));
CREATE TABLE jiffy_compensation_reset(userid INT, dayInUTC BIGINT, zoneOffset INT, currentcompensation BIGINT, manual BOOLEAN, rowState INT, serverTimeStamp BIGINT, lastChanged BIGINT, primary key(userid, DayInUTC));
CREATE TABLE jiffy_times (userid BIGINT NOT NULL, starttime BIGINT, stoptime BIGINT, rowState INT, note TEXT, startzone TEXT, stopzone TEXT, uuidM BIGINT, uuidL BIGINT, ownerUuidM BIGINT, ownerUuidL BIGINT, local int, serverTimeStamp BIGINT, lastChanged BIGINT, worktime BOOLEAN, locked BIGINT, primary key(uuidM, uuidL));
CREATE TABLE jiffy_surroundings (uuidM BIGINT, uuidL BIGINT, rowState INT, local INT, lastChanged BIGINT, serverTimeStamp BIGINT, entryUuidM BIGINT, entryUuidL BIGINT, type INT, longitude DOUBLE, latitude DOUBLE, accuracy FLOAT, primary key(uuidM, uuidL));
CREATE TABLE jiffy_purchases (userid INT , itemid VARCHAR(250) NOT NULL, status VARCHAR(10), orderid VARCHAR(200), purchasetime BIGINT, lastChanged BIGINT, rowState INT, local int, purchaseToken TEXT, serverTimeStamp BIGINT, primary key(userid, itemid));
CREATE TABLE jiffy_preferences(userid INT, name varchar(50), value varchar(60), rowState INT, serverTimeStamp BIGINT, lastChanged BIGINT, primary key(userid, name));
CREATE TABLE jiffy_nfc_badge (userId INT, uuidM BIGINT, uuidL BIGINT, name TEXT, local TEXT, rowState INT, lastChanged BIGINT, serverTimeStamp BIGINT, primary key(uuidM, uuidL));
CREATE TABLE jiffy_nfc_link (userId INT, badgeUuidM BIGINT, badgeUuidL BIGINT, ownerUuidM BIGINT, ownerUuidL BIGINT, local TEXT, rowState INT, lastChanged BIGINT, serverTimeStamp BIGINT, primary key(badgeUuidM, badgeUuidL, ownerUuidM, ownerUuidL));
CREATE TABLE log(_id INTEGER PRIMARY KEY, timeStamp BIGINT, type TEXT, note TEXT);
CREATE INDEX jiffy_start_time on jiffy_times (starttime desc);
CREATE UNIQUE INDEX id_index_override_work_times on jiffy_override_worktimes (userid, UTC, zoneOffset);
CREATE INDEX last_utc_jiffy_compensation_cache on jiffy_compensation_cache (userId, dayInUTC);
CREATE UNIQUE INDEX id_index_compensation on jiffy_compensation (uuidM, uuidL);
CREATE INDEX active_jiffy_time_tree on jiffy_time_tree (rowState, archived);
CREATE INDEX last_start_time_per_owner on jiffy_times (ownerUuidM, ownerUuIdL, startTime);
